### ISSUE TITLE
User @ Mentions

### ISSUE THREAD

**Issue by jessemillar** [microsoft/azure-devops-go-api#40]
If I use the in-browser GUI editor to create or modify a DevOps wiki page, I can @ mention a user (e.g. `@Jake Pearson`) and it makes a link to their account and sends them an email notification. When I manually pull down the Git repo that represents the wiki, I can see the raw user ID (e.g. `@<1601DE0C-4613-60D7-A201-537155816713>`) instead of the @ mention in the created wiki page implying that the GUI is doing some sort of call on the backend to change a manual @ mention into that GUID.

When I use `wiki.client.CreateOrUpdatePage(...)` to push a string containing a user's ID (e.g. `@Jake Pearson`), no linking occurs. When I push the GUID, the page displays with the raw GUID instead of the nice `@Jake Pearson`. Is there a flag or something I need to flip in the `wiki.client` to make this work? Or is it simply not possible via the API?

**Comment by tedchamb** [comment]
@jessemillar , you can find some information in this api in the official [REST docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create%20or%20update?view=azure-devops-rest-5.1), although I don't think it covers this scenario.  I recommend using [Fiddler](https://www.telerik.com/fiddler) to capture REST traffic while doing the operation using the web browser.  This should give you more details about the specific request.  I will also contact the team that owns this API, and see if they can chime in.

**Comment by harshit283** [comment]
@jessemillar Ideally linking should happen for @mentions while using the Wiki Rest Api.
Please note that you should use @GUID  instead of @person-name syntax.
Also make sure that the GUID you are using is valid, we can verify validity of GUID by inserting it into a wiki page and checking if the expected @person-name appears in the preview. If you are still viewing the raw Guid then that Guid might be invalid.

We were not able to repro the issue from our side. If you want us to investigate into this further then please share your account details.
