### ISSUE TITLE
Release Definitions data not populating

### ISSUE THREAD

**Issue by dipndawtz** [microsoft/azure-devops-go-api#46]
I'm trying to retrieve the environments/variables of a release definition using this thin wrapper. When I run the GetReleaseDefinitions function I get the details I'm expecting back like name, id, revision, but it seems like most of the more detailed information is nil. I can confirm using the URL that it returns that the Environment map and variables map both have data in them but both come back as nil from the wrapper.

**Comment by tedchamb** [comment]
@dipndawtz , this is due to a very common pattern used by the AzureDevOps REST endpoints.  Many times when you get a list of resources, the data on those resources are sparsely populated.  This is done to reduce the response size.  Once you have the list of definitions, you can then call then call the `GetReleaseDefinition` method to get the full definition details for the ones you care about.

You should also take a look at the `propertyFilters` arg for the `GetReleaseDefinitions` method in the [docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/list?view=azure-devops-rest-5.1), it looks like you can tell the method which additional properties you would like to have returned.
