### ISSUE TITLE
policy.CreatePolicyConfiguration fails with error when trying to unmarshall response from azdo 

### ISSUE THREAD

**Issue by nmiodice** [microsoft/azure-devops-go-api#59]
The API call for `CreatePolicyConfiguration` fails with the error described below. My investigation leads me to believe that the error is occurring during the response unmarshalling phase.

**API call**
https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/policy/client.go#L26

**Sample code**
```go
	createdPolicy, err := clients.PolicyClient.CreatePolicyConfiguration(clients.Ctx, policy.CreatePolicyConfigurationArgs{
		Configuration: policyConfig,
		Project:       projectID,
	})

	if err != nil) {
		return fmt.Errorf("Error creating policy in Azure DevOps: %+v", err)
	}
```

**Error Response**
```
Error: Error updating policy in Azure DevOps: parsing time ""2020-04-28T19:17:13.1093738"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"
```

**Investigation**
This is similar to the issue raised in https://github.com/microsoft/azure-devops-go-api/issues/17. The fix put forward in that issue, however, is not applicable here because the time returned from the server does not equal `0001-01-01T00:00:00`.

**Note** The policy is actually created in AzDO, which leads me to believe that the unmarshalling error is for this field specifically: https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/policy/models.go#L32

**Comment by tmeckel** [comment]
@nmiodice just wrote @mozehgir an email about the situation here with the GO API. I've the impression that nobody really maintains the GO API, because @tedchamb got assigned to another job and thus the GO API is kinda abandoned. 

Especially #47 prevents us from implementing ANY kind of support for permission related stuff in the Terraform provider. That's why my own PR https://github.com/microsoft/terraform-provider-azuredevops/pull/238, about the security framework and the first two permission resource definitions, is on hold for a couple of weeks now.

A very disappointing situation.

**Comment by nmiodice** [comment]
:/

**Comment by nmiodice** [comment]
Related issue in developer community: https://developercommunity.visualstudio.com/content/problem/1010676/policycreatepolicyconfiguration-fails-with-error-w.html

**Comment by tedchamb** [comment]
I am working with Azure DevOps leadership to find a team to pick up maintenance of the SDK going forward.  In the meantime, if I can carve out some free time outside of work, I will do a sweep of the open issues and fix what I can.  

Until these issues get addressed, I recommend the following:
1. Keep submitting issues you find to this repo
2. fork the repo so you can make your own fixes and tweaks
3. create PRs back to this repo for any fixes that do not affect the auto-generated code.

cc: @edglas1 

Thanks,
Ted

**Comment by tmeckel** [comment]
@tedchamb I think all people working on the Terraform Provider for Azure DevOps are really appreciate your willingness to work on the DevOps GO API aside your normal job as long as no new maintainer has been found!!!! As I mentioned above I'm in contact with @mozehgir, who's the new Program Manager for the Azure DevOps Provider, and I suggested that he takes the DevOps GO API under his oversight as well. It's the only logical consequence, because the DevOps GO API is the foundation of the provider. Perhaps you could get in touch with him and discuss this any further. I copy @nmiodice for reference.

**Comment by mozehgir** [comment]
Let me look in to this and get back to all of you.

**Comment by nmiodice** [comment]
FYI I've implemented a PR @tedchamb @mozehgir

https://github.com/microsoft/azure-devops-go-api/pull/60/files

**Comment by tedchamb** [comment]
@nmiodice , if this property is returning a date that is not in the standard format, then it is a service side bug.  That doesn't mean we can't create a work around, but the longterm fix is to fix the api.

**Comment by nmiodice** [comment]
@tedchamb I agree. I was "instructed" to create an issue here - https://developercommunity.visualstudio.com/content/problem/1010676/policycreatepolicyconfiguration-fails-with-error-w.html

Is there a better way to submit the bug?

**Comment by nmiodice** [comment]
I'll test this early next week and let you know if the fix merged in works for the API we are using. Thanks @tedchamb!

**Comment by tedchamb** [comment]
@nmiodice , sorry again for the slow turn around on this.  It should be fixed now.  If you have any issues with the fix, let me know.

PR #65
Release: https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv5.1.0-b1

**Comment by nmiodice** [comment]
I wanted to circle back and confirm that this issue is resolved:

```
=== RUN   TestAccAzureDevOpsBranchPolicy_CreateAndUpdate
--- PASS: TestAccAzureDevOpsBranchPolicy_CreateAndUpdate (16.23s)
PASS
```
