### ISSUE TITLE
Support for Azure DevOps Service API version 6.0

### ISSUE THREAD

**Issue by simongottschlag** [microsoft/azure-devops-go-api#93]
Hi!

I would like to know what the plans are for the api version 6? Is there anything that someone from outside of Microsoft can do to help?

Regards,
Simon

**Comment by richardgavel** [comment]
It seems that these client and model .go files are generated, according to the existing files. Is there something blocking keeping it up to date?

**Comment by aleqsss** [comment]
@richardgavel where does it seem like these are updated? Do you mean somewhere else outside of this repository?

If you look at the [taskagent](https://github.com/microsoft/azure-devops-go-api/tree/09c8cad426a653fc76cdbfb915d3d11114b4d8e8/azuredevops/taskagent) [client.go](https://github.com/microsoft/azure-devops-go-api/blob/09c8cad426a653fc76cdbfb915d3d11114b4d8e8/azuredevops/taskagent/client.go) and [model.go](https://github.com/microsoft/azure-devops-go-api/blob/09c8cad426a653fc76cdbfb915d3d11114b4d8e8/azuredevops/taskagent/models.go), it seems like they are generated pre API version 6.0 since they are not implementing [TaskAgentPoolOptions](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/add?view=azure-devops-rest-6.0#taskagentpooloptions) which was introduced in version 6.0.

Please see my created issue: #90

Thank you!

**Comment by richardgavel** [comment]
@aleqsss Those are exactly what I am referring to, all the core files within the GO SDK have comments that they are files generated of "something". If you look at another binding, like Node/TS, its generated as well (https://github.com/microsoft/azure-devops-node-api/blob/master/api/ReleaseApi.ts), which is at 6.0-preview.1. So for Go, we're just waiting for someone to actually **run** the generation, which is the annoying thing.

**Comment by aleqsss** [comment]
If you look at my created issue #90, you can see that I ask them to run this generation. 🙂 Hopefully someone will take action upon this soon, it has been lying around there for some time now.

**Comment by aleqsss** [comment]
@richardgavel FYI

As a reference, I've also got the issue [Agent Pool - Azure virtual machine scale set #204](https://github.com/microsoft/terraform-provider-azuredevops/issues/204) open in the [terraform-provider-azuredevops](https://github.com/microsoft/terraform-provider-azuredevops/issues/204) repository.

**Comment by mvanderlyn27** [comment]
Hello, Any update on this? Would be very helpful to be able to use the 6.0 API

**Comment by favoretti** [comment]
In the meantime there's API 6.1.. devops terraform provider could use a lot of extra functionality that's currently being blocked by a lagging SDK. Anyone?

**Comment by tedchamb** [comment]
@goflores , let me know if you need help updating the sdk to 6.0, 6.1.  Shouldn't be much work.

**Comment by favoretti** [comment]
@tedchamb I guess he's busy, would you be so kind to take a stab at it? Would be very much appreciated by a lot of people :)

**Comment by goflores** [comment]
@favoretti Sorry, I sync'd with @tedchamb but didn't post an update here. We've gone through the work needed for the update and I'll be working to update the SDK to 6.0  and 6.1

**Comment by favoretti** [comment]
Awesome news! Thanks so much!

**Comment by xuzhang3** [comment]
@goflores Is there an ETA of v6.x SDK?

**Comment by gabrielmccoll-rlg** [comment]
also very excited for this to happen, trying to setup ADO via Terraform and would love the extra functionality

**Comment by richardgavel** [comment]
Just saw this in a consuming repo so hopefully there will be traction soon: https://github.com/microsoft/terraform-provider-azuredevops/issues/419#issuecomment-961283236

**Comment by nechvatalp** [comment]
Hello everyone, new version with support for Azure DevOps API version 6.0 has been released.

You can get it using
`go get github.com/microsoft/azure-devops-go-api/azuredevops/v6`

Thank you for your patience.
